server:
  port: 80


spring:
  application:
    name: ordercenter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: ordercenter80 # 修改主机名称（Eureka Instance中status中的显示问题）
    prefer-ip-address: true # 访问路显示IP地址

