
server:
  port: 8002

spring:
  application:
    name: paycenter
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.87.66:13306/vongfong?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: icopdb-dev
    password: icopdb

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.icop.vongfong.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://eureka7002.com:7002/eureka # 单机版
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
   instance-id: paycenter8002 # 修改主机名称（Eureka Instance中status中的显示问题）
   prefer-ip-address: true # 访问路显示IP地址