
server:
  port: 3388

spring:
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 106.54.87.66
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: vongfongtest # 设置消费者群组，避免消息被重复消费
  application:
    name: microcloud-stream-provider


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka # 单机版
      # defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
    # eureka-server-u-r-l-context:
  instance:  # actuator微服务信息配置
    instance-id: producer3377 # 修改主机名称（Eureka Instance中status中的显示问题）
    prefer-ip-address: true # 访问路显示IP地址:
    # lease-renewal-interval-in-seconds: 1 # 向Eureka客户端向服务端发送心跳的时间间隔，默认30s
    # lease-expiration-duration-in-seconds: 90 # Eureka服务端收到最后一次心跳的等待时间上限，默认90s,超时剔除服务

